import { useState } from 'react'
import './Popup.css'
import { sendMessageToBackground } from '../utils'

export const Popup = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext'
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const handleSubmit = async (event) => {
    event.preventDefault()
    console.log(email, password)
    const { success } = await sendMessageToBackground({
      action: 'SIGNUP_EMAIL_PASSWORD',
      data: { email, password },
    })
    console.log('success', success)
  }

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <form onSubmit={handleSubmit}>
          <label>
            Email:
            <input type="text" value={email} onChange={(event) => setEmail(event.target.value)} />
          </label>
          <label>
            Password:
            <input
              type="password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
            />
          </label>
          <input type="submit" value="Submit" />
        </form>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Popup
